# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.7

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: "Download dependencies"
          command: go mod download
      - run:
          name: "Run tests"
          command: go test -v ./...
      - run:
          name: "Ensure 100% coverage"
          command: |
            go test -cover ./... | grep "coverage: 100.0% of statements"
